language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install pipenv==2018.10.13  # 2018.11.14 is broken. Revisit this once it's fixed.
  - pipenv install --dev -e ".[s3-backend,redis-backend,trigger,testing]"

script:
  - pytest --cov

after_success:
 - codecov
