language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install codecov
  - pip install ".[s3-backend,redis-backend,trigger]"
# command to run tests
script:
  - coverage run -m pytest
after_success:
 - codecov
