---

DEVEAST:
    project_name: drift-config
    aws_region: ap-southeast-1  # Location of this lambda
    environment_variables:
        S3_ORIGIN_URL: s3://relib-test/directive-games  # The config origin.
        TIER_NAME: DEVEAST
    tags:
        tier: DEVEAST
        service-name: drift-config
        service-type: zappa
        Name: DEVEAST-drift-config        
    vpc_config:
        SubnetIds: [subnet-11518a66, subnet-d00eb5b5]
        SecurityGroupIds: [sg-841683e1]
    use_apigateway: false
    events:
    -
        # The tier is in a different region than the s3 config location so we
        # cannot use an s3:put event trigger. Instead we will poll periodically.
        function: driftconfig.lambdas.refresh_cache.do_update_cache
        expression: "rate(1 minute)" # When to execute it (in cron or rate format)

    # Zappa control parameters
    s3_bucket: zappa-deveast
    log_level: INFO



DEVNORTH:
    project_name: drift-config
    aws_region: eu-west-1  # Location of this lambda
    environment_variables:
        S3_ORIGIN_URL: s3://relib-test/directive-games  # The config origin.
        TIER_NAME: DEVNORTH
    tags:
        tier: DEVNORTH
        service-name: drift-config
        service-type: zappa
        Name: DEVNORTH-drift-config        
    vpc_config:
        SubnetIds: [subnet-aef280cb, subnet-8544def2]
        SecurityGroupIds: [sg-ce4849ab]
    use_apigateway: false
    events:
    -
        # The tier is in the same region as the s3 config location so we can set
        # up an s3:put event trigger.
        function: driftconfig.lambdas.refresh_cache.on_config_update
        event_source:
            arn: arn:aws:s3:::relib-test
            events: [ 's3:ObjectCreated:*' ]

    # Zappa control parameters
    s3_bucket: zappa-devnorth
    log_level: INFO



LIVENORTH:
    project_name: drift-config
    aws_region: eu-west-1  # Location of this lambda
    environment_variables:
        S3_ORIGIN_URL: s3://relib-test/directive-games  # The config origin.
        TIER_NAME: LIVENORTH
    tags:
        tier: LIVENORTH
        service-name: drift-config
        service-type: zappa
        Name: LIVENORTH-drift-config        
    vpc_config:
        SubnetIds: [subnet-0cdba47b, subnet-41faad24]
        SecurityGroupIds: [sg-78c53f1c]
    use_apigateway: false
    events:
    -
        # The tier is in the same region as the s3 config location so we can set
        # up an s3:put event trigger.
        function: driftconfig.lambdas.refresh_cache.on_config_update
        event_source:
            arn: arn:aws:s3:::relib-test
            events: [ 's3:ObjectCreated:*' ]

    # Zappa control parameters
    s3_bucket: zappa-livenorth
    log_level: INFO


